version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "4000:4000"
    restart: always
  db:
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro