#nginx.yml
---
- name: Este Playbook instala nginx
  hosts: web
  tasks:
    - name: Esta tarea instala nginx
      apt: name=nginx state=latest
    - name: Añadir fichero index.html
      template:
       src: /home/vagrant/vm_aws_terraform/index.nginx-debian.html
       dest: /var/www/html/index.nginx-debian.html
    - name: Arrancar Nginx
      service:
       name: nginx
       state: started